### ISSUE TITLE
Missing config.json and DS18B20 Temp Sensor Issue

### ISSUE THREAD

**Issue by oculardynamic** [xperiments-in/xtouch#129]
**Describe the bug**
XTouch updated properly OTA, but upon reboot i get error "Missing config.json"

**To Reproduce**
On boot up

**Expected behavior**
Should boot up

**XTOUCH (please complete the following information):**
Newest Version

**Printers (please complete the following information):**
For P1P

I also noticed once I was able to remedy the missing config file detailed in the next post for anyone else looking for help that my DS18B20 chamber temp sensors are no longer working. They are stuck on "5", wondering if the update perhaps broke communication to sensor?

**Comment by oculardynamic** [comment]
I was able to remedy the issue and will post it here for anyone else who comes across it

Create a Configuration File:

Use the online configuration [TOOL](https://xperiments.in/xtouch-bin/config.html) to generate a config.json file.
Place it on the root directory of the SD card.
Your SD card is now properly initialized with the required configuration. This configuration will enable the xtouch screen to connect to your WiFi network and BambuLab servers during the installation process.

**Comment by EnergySaversAi** [comment]
I have the same issue with chamber temperature stuck on 5

**Comment by oculardynamic** [comment]
> I have the same issue with chamber temperature stuck on 5

Good to know it was the update that broke the temp sensor. Hopefully we can get that fixed

**Comment by wi1k1n** [comment]
I have the same setup, but instead of OTA I flashed firmware using online flashing tool. No issues with DS18B20 🤔

**Comment by EnergySaversAi** [comment]
I also flashed by firmware.bin no temp sensor always 5

**Comment by oculardynamic** [comment]
I think i read on facebook you have to reformat the sdcard if you do the OTA

**Comment by xperiments** [comment]
All of you, can say what printer model. I am unable to reproduce it in P1P

**Comment by puckshaw** [comment]
My chamber temp sensor is stuck on 5 also. P1S. OTA update and created new config file.

**Comment by xperiments** [comment]
And formatted SD?

**Comment by xperiments** [comment]
Could also you post in zip the contents of xtouch folder

**Comment by xperiments** [comment]
I am closing it, as I have tested and retested and the only logic here to fail is that you have not formatted the SD card

Please

Format your SD card
Copy config.json to it
Reboot screen
Setup touch etc

Please reopen if them does not work and also come to Discord where is more easy to help in this things

THX!!

**Comment by xperiments** [comment]
OK reopened as I have found the bug...

Working on it...

**Comment by xperiments** [comment]
Fixed in v0.9.104.

Install. Set chamber on another time
Reboot

**Comment by oculardynamic** [comment]
> Fixed in v0.9.104.
> 
> Install. Set chamber on another time Reboot

OTA Installed, chamber still showing 5, but i'm not exactly what "Set Chamber on another time" means? I still dont see it in my settings. Should i set the chamber sensor to "1" in the settings files as its shows set to "0"

**Comment by xperiments** [comment]
Have y formated the SD?

**Comment by Moe555** [comment]
I had the same issue.
I can confirm that after formatting SD, copying config.json, reinstalling via USB and setting the chamber temp to on afterwards it's working fine again.
